DROP TABLE IF EXISTS bookings;

DROP TABLE IF EXISTS requests;

DROP TABLE IF EXISTS comments;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS items;

CREATE TABLE IF NOT EXISTS users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "USERS_pk"
            PRIMARY KEY,
    user_name VARCHAR NOT NULL,
    email     VARCHAR NOT NULL
        CONSTRAINT users_pk
            UNIQUE
);

CREATE TABLE IF NOT EXISTS items
(
    item_id      BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT item_pk
            PRIMARY KEY,
    item_name    VARCHAR NOT NULL,
    description  VARCHAR,
    is_available BOOLEAN NOT NULL,
    owner_id     BIGINT  NOT NULL,
    request_id   BIGINT
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT bookings_pk
            PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id    BIGINT    NOT NULL
        CONSTRAINT bookings_items_null_fk
            REFERENCES items
            ON UPDATE CASCADE ON DELETE CASCADE,
    booker_id  BIGINT    NOT NULL
        CONSTRAINT bookings_users_null_fk
            REFERENCES users
            ON UPDATE CASCADE ON DELETE CASCADE,
    status     VARCHAR   NOT NULL
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id        BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT requests_pk
            PRIMARY KEY,
    description       VARCHAR,
    requestor_id      BIGINT    NOT NULL
        CONSTRAINT foreign_key_name
            REFERENCES users,
    created_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT comments_pk
            PRIMARY KEY,
    text       TEXT,
    item_id    BIGINT NOT NULL
        CONSTRAINT comments_items_null_fk
            REFERENCES items (item_id)
            ON DELETE CASCADE,
    author_id  BIGINT NOT NULL
        CONSTRAINT comments_users_null_fk
            REFERENCES users (user_id)
            ON DELETE CASCADE,
    created    TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
